### ISSUE TITLE
Add builds to releases

### ISSUE THREAD

**Issue by abueide** [TokTok/jvm-toxcore-c#6]
It would be nice if there was a jar file build in the releases section

**Comment by iphydf** [comment]
It's not very useful, because this is the C binding, which means you also need to compile the native library, and you'll still need to do that yourself. I can upload some compiled version of it, but it'll depend on a certain libc version. Anyway you probably want to be coding against jvm-toxcore-api, not jvm-toxcore-c. The API is platform independent, and we have a bintray repo for it: org.toktok/tox4j-api_2.11.

**Comment by abueide** [comment]
Ah okay, thanks.
